### ISSUE TITLE
wal-g configuration to store the backup to openstack swift storage

### ISSUE THREAD

**Issue by manojaitha** [bitnami/bitnami-docker-wal-g#2]
Hi, we have installed postgres container using kubernetes, now want to configure wal-g to backup/ restore purpose.
Can we use openStack Swift storage as remote backup store?

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure about this.
  If you can use the swift storage as a mount point, you will be able to use it. If you want to use it in other way, I suggest you to ask for the needed parameters in a wal-g forum.

**Comment by rafariossaa** [comment]
Hi,
 Due to inactivity, I am closing this issue.
 Please, don't hesitate to reopen it if needed.
