### ISSUE TITLE
Version 1.0 Released!

### ISSUE THREAD

**Issue by Silvenga** [bitnami/bitnami-docker-wal-g#3]
**Description**

Rejoice for version 1.0 of wal-g has been released! Long let it be stable. https://github.com/wal-g/wal-g/releases/tag/v1.0

Is this a bitnami server side change that needs to happen? Or can I open a PR somewhere?

**Comment by carrodher** [comment]
Thanks for letting us know. New versions are tracked automatically by our test & release pipeline, but when the detected version is a new major (in this case the version was bumped from 0.X.X to 1.X.X) there are some manual steps required to add the new branch to the system.

I just checked the new major version was detected so the team should start looking into this soon, usually, within the following 1 or 2 weeks the new major version should be tested and released, in the same way, the previous version will be deprecated and replaced by the new one.

**Comment by carrodher** [comment]
The new branch was released some days ago, you can find the code at https://github.com/bitnami/bitnami-docker-wal-g/tree/master/1/debian-10 and the images in the different registries, such as DockerHub (https://hub.docker.com/layers/bitnami/wal-g/1.0.0/images/sha256-a7af3ce7467b5a5e0fd88351ed3ed2a396694576f248cf2b8bde07e95dd8ef72?context=explore)

Thanks for using this image. I am closing this issue.
